// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn5rxtY7sxMV6eflkthNi291FJk8p0rx8',
    appId: '1:672878091285:web:5f100b56c7f3eaf310421c',
    messagingSenderId: '672878091285',
    projectId: 'chat-flutter-12799',
    authDomain: 'chat-flutter-12799.firebaseapp.com',
    storageBucket: 'chat-flutter-12799.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjZTPhXMiGVlJJtpTbYsk2mj-ZjqERH4o',
    appId: '1:672878091285:android:48a65d8123d25fd510421c',
    messagingSenderId: '672878091285',
    projectId: 'chat-flutter-12799',
    storageBucket: 'chat-flutter-12799.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp2FRX2_YOX4JuGvDocOiC6G_VDE-sFgE',
    appId: '1:672878091285:ios:9b02bf92e475c78710421c',
    messagingSenderId: '672878091285',
    projectId: 'chat-flutter-12799',
    storageBucket: 'chat-flutter-12799.firebasestorage.app',
    androidClientId: '672878091285-m0n64cpi7l0vlds8u0q5a49so85ufkfo.apps.googleusercontent.com',
    iosClientId: '672878091285-kmu468j0d0va4ng1ma6g0ek21p9o0b1n.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp2FRX2_YOX4JuGvDocOiC6G_VDE-sFgE',
    appId: '1:672878091285:ios:9b02bf92e475c78710421c',
    messagingSenderId: '672878091285',
    projectId: 'chat-flutter-12799',
    storageBucket: 'chat-flutter-12799.firebasestorage.app',
    androidClientId: '672878091285-m0n64cpi7l0vlds8u0q5a49so85ufkfo.apps.googleusercontent.com',
    iosClientId: '672878091285-kmu468j0d0va4ng1ma6g0ek21p9o0b1n.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn5rxtY7sxMV6eflkthNi291FJk8p0rx8',
    appId: '1:672878091285:web:74516a0feaf0cac010421c',
    messagingSenderId: '672878091285',
    projectId: 'chat-flutter-12799',
    authDomain: 'chat-flutter-12799.firebaseapp.com',
    storageBucket: 'chat-flutter-12799.firebasestorage.app',
  );

}